# Generated by Django 5.1.3 on 2024-11-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('any', 'Anyone'), ('email', 'Email_required'), ('draft', 'Draft')], default='email', max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pub', 'published'), ('soon', 'Coming Soon'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
